# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DTCoreTextDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'DTCoreText', '1.6.21'

  # Pods for DTCoreTextDemo

  target 'DTCoreTextDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DTCoreTextDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
